language: php
sudo: required
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - NC_BRANCH=master
  matrix:
    - NC_DATABASE=mysql

matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 5.5
      env: NC_DATABASE=sqlite
    - php: 5.5
      env: NC_DATABASE=pgsql
    - php: 5.6
      env: NC_DATABASE=sqlite
    - php: 5.6
      env: NC_DATABASE=pgsql
    - php: 7.0
      env: NC_DATABASE=sqlite
    - php: 7.0
      env: NC_DATABASE=pgsql

install:
  - phpenv config-add tests/travis/php.ini
  - ./tests/prepare-ci-tests.sh

script:
  - cd ${TRAVIS_BUILD_DIR}/../owncloud/apps/spreedme
  - phpunit -c phpunit.xml
  - phpunit -c phpunit.integration.xml
