#!/bin/bash -e

export PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin

invoke() {
    if [ -x /usr/sbin/invoke-rc.d ]; then
        invoke-rc.d $1 $2
    else
        /etc/init.d/$1 $2
    fi
}

case "$1" in
    configure)
        if [ -e "/usr/lib/owncloud/www/core/shipped.json" ]; then
            sed -i 's|"shippedApps": \[$|"shippedApps": \["spreedme",|;' /usr/lib/owncloud/www/core/shipped.json
        fi
        if [ -e "/etc/init.d/spreed-webrtc" ]; then
            invoke spreed-webrtc restart || true
        fi
        if [ -e "/etc/init.d/php5-fpm" ]; then
            invoke php5-fpm restart || true
        fi
        if [ -s "/etc/owncloud/config.php" ]; then
            if [ -x "/usr/bin/occ" ]; then
                set +e
                /usr/bin/occ upgrade
                rc=$?
                set -e
                if [ "$rc" != "0" ] && [ "$rc" != "3" ]; then
                    echo "****************************************************************"
                    echo "** Automatic update failed, please run 'occ upgrade' manually **"
                    echo "** after the installation to finish upgrading the spreedme    **"
                    echo "** ownCloud application!                                      **"
                    echo "****************************************************************"
                fi
            else
                echo "***************************************************************"
                echo "** Please run 'occ upgrade' after the installation to finish **"
                echo "** upgrading the spreedme ownCloud application!              **"
                echo "***************************************************************"
            fi
        fi
        ;;

    triggered)
        if [ -e "/usr/lib/owncloud/www/core/shipped.json" ]; then
            sed -i 's|"shippedApps": \[$|"shippedApps": \["spreedme",|;' /usr/lib/owncloud/www/core/shipped.json
        fi
        if [ -e "/etc/init.d/php5-fpm" ]; then
            invoke php5-fpm restart || true
        fi
        ;;

    abort-upgrade|abort-remove|abort-configure)
        ;;

    *)
        echo "postinst called with unknown argument '$1'" 1>&2
        exit 1
        ;;
esac

#DEBHELPER#
