#!/bin/bash -e

export PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin

export OCC=/usr/bin/occ.nextcloud

invoke() {
    if [ -x /usr/sbin/invoke-rc.d ]; then
        invoke-rc.d $1 $2
    else
        /etc/init.d/$1 $2
    fi
}

mark_shipped() {
    if [ -x "/usr/share/spreedbox-nextcloud/spreedbox-mark-shipped" ]; then
        /usr/share/spreedbox-nextcloud/spreedbox-mark-shipped spreedme
    else
        sed -i 's|"shippedApps": \[$|"shippedApps": \["spreedme",|;' /usr/lib/nextcloud/www/core/shipped.json
        sed -i 's|"alwaysEnabled": \[$|"alwaysEnabled": \["spreedme",|;' /usr/lib/nextcloud/www/core/shipped.json
    fi
}

case "$1" in
    configure)
        cp --no-clobber "/usr/share/nextcloud-spreedme/config/config.php.in" "/etc/spreedme/nextcloud/config.php"
        cp --no-clobber "/usr/share/nextcloud-spreedme/extra/static/config/OwnCloudConfig.js.in" "/etc/spreedme/nextcloud/OwnCloudConfig.js"
        if [ -e "/usr/lib/nextcloud/www/core/shipped.json" ]; then
            mark_shipped
        fi
        if [ -s "/etc/nextcloud/config.php" ]; then
            if [ -x "$OCC" ]; then
                set +e
                $OCC upgrade
                rc=$?
                set -e
                if [ "$rc" != "0" ] && [ "$rc" != "3" ]; then
                    echo "****************************************************************"
                    echo "** Automatic update failed, please run 'occ.nextcloud upgrade' manually **"
                    echo "** after the installation to finish upgrading the spreedme    **"
                    echo "** Nextcloud application!                                     **"
                    echo "****************************************************************"
                fi
            else
                echo "***************************************************************"
                echo "** Please run 'occ.nextcloud upgrade' after the installation to finish **"
                echo "** upgrading the spreedme Nextcloud application!             **"
                echo "***************************************************************"
            fi
        fi
        ;;

    triggered)
        if [ -e "/usr/lib/nextcloud/www/core/shipped.json" ]; then
            mark_shipped
        fi
        dpkg-trigger spreedbox-restart-php-fpm
        ;;

    abort-upgrade|abort-remove|abort-configure)
        ;;

    *)
        echo "postinst called with unknown argument '$1'" 1>&2
        exit 1
        ;;
esac

#DEBHELPER#
